# Generated by Django 4.0.4 on 2022-05-23 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chewapp", "0002_profiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="category",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="qty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="menuItem",
            field=models.ManyToManyField(
                related_name="categories", to="chewapp.menuitem"
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="stock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="couponcode",
            name="code",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=65535)),
                ("price", models.FloatField()),
                ("qty", models.IntegerField(default=0)),
                ("status", models.IntegerField()),
                (
                    "menu_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chewapp.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="chewapp.order",
                    ),
                ),
            ],
        ),
    ]
