# Generated by Django 4.0.4 on 2022-05-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chewapp", "0003_remove_menuitem_category_cartitem_qty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(default="", max_length=255),
        ),
    ]
