# Generated by Django 4.0.4 on 2022-05-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewapp', '0005_menuitem_imgname_menuitem_menuimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menuImg',
            field=models.ImageField(default='chewapp/static/chewapp/FoodImages/testing.jpg', upload_to='static/'),
        ),
    ]
