# Generated by Django 4.0.4 on 2022-05-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chewapp', '0005_account_created_at_account_updated_at_and_more'),
        ('chewapp', '0006_alter_menuitem_menuimg'),
    ]

    operations = [
    ]
