# Generated by Django 4.0.4 on 2022-05-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewapp', '0007_merge_20220524_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menuImg',
            field=models.ImageField(default='static/chewapp/static/chewapp/FoodImages/testing.jpg', upload_to='static/'),
        ),
    ]
